check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.32.3
  build-stratergy: "Source"
  registry: "quay.io"
  registry-org: "thoth-station"
  registry-project: "qeb-hwt-webhook-receiver"
  registry-secret: "thoth-station-thoth-pusher-secret"
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "qeb-hwt-webhook-receiver"
  overlay-contextpath: "qeb-hwt-github-app/overlays/test/imagestreamtag.yaml"
